services:
  backend:
    build: ./backend
    container_name: simulador-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    container_name: simulador-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
